type: pie-chart
# Table ID
dataSource: ""
# Column ID for labels
labelColumn: ""
# Column ID for values
valueColumn: ""
# Format: Array of text format strings. See [Text Format Documentation](../../format/data/text.md)
heading: []
# Column ID to sort by
sortBy: ""
# Sort direction
sortType: ""
# Filter object
filter: null
# Items per page
itemsPerPage: 0
# Width format
width: ""
# Alignment format
alignment: ""
# Heading alignment format
headingAlignment: ""
# Format: "m:16px". See [Spacing Format Documentation](../../format/styles/spacing.md)
margin: ""
# Heading margin format
headingMargin: ""
# Typography format
typography: ""
# Heading typography format
headingTypography: ""
# Color sequence
colorSequence: ""
# Show legend
legend: false  # true/false

